name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: |
        ./target/release/minicomp miniout.elf "avg(x, y) = (x + y)/2; quad(x, a, b, c) = a*x*x + b*x + c"
        chmod +x miniout.elf
        ./miniout.elf
        objdump -M intel -d miniout.elf
        ls -la miniout.elf | grep 764 # check the file size
        ./miniout.elf | grep -a "Z <- result"
        ./miniout.elf | grep -a "D <- result"
      
